### ISSUE TITLE
Release artifacts on Hugging Face for better discoverability

### ISSUE THREAD

**Issue by NielsRogge** [vmicheli/delta-iris#1]
Hi there,

Congrats on this work! Niels here from Hugging Face, we were wondering whether it'd be possible to share artifacts (models, datasets, potential demos in the form of a 🤗 Space) on the hub.

The paper page is here: https://huggingface.co/papers/2406.19320.

I see the checkpoint is currently being stored on Google Drive which makes it pretty hard to find for people. One could leverage the PyTorchModelHubMixin class to push and load the PyTorch checkpoint from/to the hub as explained here: https://huggingface.co/docs/hub/models-uploading#upload-a-pytorch-model-using-huggingfacehub

Furthermore, you can then link the model to the paper, add tags to the model card (like "world-model") so that people find this research work in an easier way.

Let me know if you need any help!

Cheers,

Niels 🤗 
ML Engineer @ HF

**Comment by vmicheli** [comment]
Hi Niels,

Thanks for your interest and your suggestions!

I have uploaded the checkpoint to the hub: https://huggingface.co/vmicheli/delta-iris.

A demo that I would find interesting would be to let users play live in the world model on the hub, but last time I checked this did not look feasible.

**Comment by NielsRogge** [comment]
Thanks a lot for doing that! Btw, if you use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/en/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) you can do `model = Agent.from_pretrained("vmicheli/delta-iris")` without requiring people to manually download the checkpoint first and creating a checkpoints directory.

Regarding the demo, Spaces also works with Docker so if you have a Docker container that could technically host anything

**Comment by vmicheli** [comment]
Thanks for the suggestions! We will keep the checkpoint loading as it is for now, and think about a potential demo on Spaces.
